name: Benchmark
# Run on `push` only for main, if not it will trigger `push` & `pull_request` on PRs at the same time
on:
  push:
    branches:
      - main
      - '*.*.x'
    paths-ignore:
      # Any update here needs to be done for `pull_request`, see below
      # and all files (test.yml, benchmark.yml, release-ci.yml, bundle-size.yml)
      - '*.md'
      # - '*.bench.ts' -> should not be ignored in this workflow
      - 'LICENSE'
      - '.dockerignore'
      - 'scripts/ci/publish.ts'
      - '.github/CODEOWNERS'
      - '.github/renovate.json'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/DISCUSSION_TEMPLATE/**'
      - '.devcontainer/**'
      - '.vscode/**'
      - 'graphs/**'
      - 'sandbox/**'
  pull_request:
    paths-ignore:
      # Any update here needs to be done for `push`, see above
      # and all files (test.yml, benchmark.yml, release-ci.yml)
      - '*.md'
      # - '*.bench.ts' -> should not be ignored in this workflow
      - 'LICENSE'
      - '.dockerignore'
      - 'scripts/ci/publish.ts'
      - '.github/CODEOWNERS'
      - '.github/renovate.json'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/DISCUSSION_TEMPLATE/**'
      - '.devcontainer/**'
      - '.vscode/**'
      - 'graphs/**'
      - 'sandbox/**'
  workflow_dispatch:

env:
  PRISMA_TELEMETRY_INFORMATION: 'prisma benchmark.yml'

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install & build
        uses: ./.github/actions/setup
        with:
          node-version: 20
          pnpm-version: 8.15.5
          skip-tsc: false

      # - name: Install codspeed-node from Git
      #   run: .github/workflows/scripts/codspeed-node-from-git main

      - name: Run benchmarks for Codspeed
        uses: CodSpeedHQ/action@v2
        with:
          run: pnpm run bench-stdout-only
          upload-url: ${{ vars.CODSPEED_DEV_UPLOAD_URL }}/upload
          token: ${{ secrets.CODSPEED_TOKEN }}
        env:
          CODSPEED_BENCHMARK: true
