name: Benchmark
on:
  push:
    branches:
      - main
    paths-ignore:
      # Any update here needs to be done for
      # - `pull_request` see below
      # - https://github.com/prisma/prisma/blob/main/.buildkite/test/buildkite-entry.sh
      # - https://github.com/prisma/prisma/blob/main/.buildkite/publish/buildkite-entry.sh
      - '*.md'
      - '.devcontainer/**'
      - '.vscode/**'
      - 'docs/**'
      - 'examples/**'
      - 'LICENSE'
      - '.github/CODEOWNERS'
      - '.buildkite/**'
      - '.dockerignore'
      - 'scripts/ci/publish.ts'
      - 'graphs/**'
  pull_request:
    paths-ignore:
      - '*.md'
      - '.devcontainer/**'
      - '.vscode/**'
      - 'docs/**'
      - 'examples/**'
      - 'LICENSE'
      - '.github/CODEOWNERS'
      - '.buildkite/**'
      - '.dockerignore'
      - 'scripts/ci/publish.ts'
      - 'graphs/**'
  workflow_dispatch:

env:
  PRISMA_TELEMETRY_INFORMATION: 'prisma benchmark.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4

      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '16'

      - run: bash .github/workflows/scripts/setup.sh
        env:
          CI: true
          SKIP_GIT: true
          GITHUB_CONTEXT: ${{ toJson(github) }}

      #  This is required as setup.sh can modify pnpm-lock.yml
      - run: rm -f ./pnpm-lock.yaml

      - name: Run benchmarks for Codspeed
        uses: CodSpeedHQ/action@v1
        with:
          run: pnpm run bench-stdout-only
          token: ${{ secrets.CODSPEED_TOKEN }}
